
tasks:
  - command: go run cmd/gopen/main.go -- preview example/hello-world/main.go 

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 9999
    onOpen: open-preview

vscode:
  extensions:
    - golang.go